from AlgorithmImports import *
from collections import defaultdict, deque
from datetime import datetime
import csv
import io
import math
import statistics


class BottleneckWinnerFreePIT(QCAlgorithm):
    """
    QuantConnect cloud backtest for the FREE_DISCOVERY Bottleneck Winner tournament.

    Design principles:
    - point-in-time fundamental universe only
    - includes delisted securities through QuantConnect's PIT universe/security master
    - joins external SEC-derived competition metrics using Symbol.CIK
    - no current-constituent universe
    - no use of future financial statement values
    - frozen model weights from research/free_stage1/frozen_spec.json

    Required project parameter for bottleneck models:
        network_url=<public/object-store CSV URL generated by sec_item1_network.py>

    Optional parameters:
        model=momentum|quality_momentum|bottleneck_core|bottleneck_momentum|bottleneck_full
        top_n=10|20|40
        start=2009-01-01
        end=2023-12-31
    """

    MODEL_WEIGHTS = {
        "momentum": {
            "momentum12": 0.70,
            "high52": 0.30,
        },
        "quality_momentum": {
            "momentum12": 0.35,
            "high52": 0.15,
            "quality": 0.30,
            "dilution": 0.20,
        },
        "bottleneck_core": {
            "demand_accel": 0.35,
            "pricing_power": 0.30,
            "competitive_scarcity": 0.35,
        },
        "bottleneck_momentum": {
            "demand_accel": 0.20,
            "pricing_power": 0.15,
            "competitive_scarcity": 0.20,
            "momentum12": 0.30,
            "high52": 0.15,
        },
        "bottleneck_full": {
            "demand_accel": 0.15,
            "pricing_power": 0.10,
            "competitive_scarcity": 0.15,
            "quality": 0.15,
            "dilution": 0.10,
            "valuation": 0.10,
            "momentum12": 0.15,
            "high52": 0.10,
        },
    }

    def initialize(self):
        start = self.get_parameter("start") or "2009-01-01"
        end = self.get_parameter("end") or "2023-12-31"
        self.set_start_date(*[int(x) for x in start.split("-")])
        self.set_end_date(*[int(x) for x in end.split("-")])
        self.set_cash(10_000_000)

        self.model_name = self.get_parameter("model") or "bottleneck_full"
        if self.model_name not in self.MODEL_WEIGHTS:
            raise ValueError(f"unknown model={self.model_name}")
        self.top_n = int(self.get_parameter("top_n") or "20")
        if self.top_n not in (10, 20, 40):
            raise ValueError("top_n must be 10, 20, or 40")

        self.network = self._load_network(self.get_parameter("network_url"))
        self.price_history = defaultdict(lambda: deque(maxlen=270))
        self.audit_rows = []
        self.one_way_cost_bps = 15.0

        # Frozen tournament cost convention: 15 bps all-in execution drag on
        # every buy/sell side, with no separate commission. Add (rather than
        # replace) an initializer so LEAN's other brokerage reality models
        # remain intact.
        self.add_security_initializer(self._initialize_security_costs)
        self.quarter_history = defaultdict(lambda: deque(maxlen=8))
        self._last_qkey = None
        self._pending_targets = []
        self._latest_scores = {}
        self._latest_feature_rows = {}
        self._selection_date = None

        self.spy = self.add_equity("SPY", Resolution.DAILY).symbol
        self.set_benchmark(self.spy)

        self.universe_settings.resolution = Resolution.DAILY
        self.universe_settings.data_normalization_mode = DataNormalizationMode.ADJUSTED
        self.add_universe(self._select_fundamentals)

        # Rebalance after universe selection at the market open.
        self.schedule.on(
            self.date_rules.every_day(),
            self.time_rules.after_market_open(self.spy, 1),
            self._rebalance_if_pending,
        )

        self.debug(
            f"FREE_DISCOVERY model={self.model_name} top_n={self.top_n} "
            f"network_rows={sum(len(v) for v in self.network.values())}"
        )

    def _initialize_security_costs(self, security):
        if security.type == SecurityType.EQUITY:
            security.set_fee_model(ConstantFeeModel(0, "USD"))
            security.set_slippage_model(ConstantSlippageModel(self.one_way_cost_bps / 10_000.0))

    # ---------- Network ----------

    def _load_network(self, url):
        # cik -> sorted list of (formation_date, metrics)
        out = defaultdict(list)
        if not url:
            if self.model_name.startswith("bottleneck"):
                self.debug("No network_url supplied; bottleneck features will be missing.")
            return out
        raw = self.download(url)
        if not raw:
            raise ValueError("network_url returned empty content")
        for row in csv.DictReader(io.StringIO(raw)):
            cik = str(row["cik"]).zfill(10)
            d = datetime.strptime(row["formation_date"][:10], "%Y-%m-%d").date()
            out[cik].append(
                (
                    d,
                    {
                        "peer_count": self._float(row.get("peer_count")),
                        "total_similarity": self._float(row.get("total_similarity")),
                        "similarity_hhi": self._float(row.get("similarity_hhi")),
                        "text_scarcity_raw": self._float(row.get("text_scarcity_raw")),
                    },
                )
            )
        for cik in out:
            out[cik].sort(key=lambda x: x[0])
        return out

    def _network_asof(self, cik, d):
        rows = self.network.get(str(cik).zfill(10), ())
        best = None
        for dt, metrics in rows:
            if dt <= d:
                best = metrics
            else:
                break
        return best

    # ---------- Fundamental state ----------

    @staticmethod
    def _float(x):
        try:
            v = float(x)
            return v if math.isfinite(v) else float("nan")
        except Exception:
            return float("nan")

    @staticmethod
    def _safe_div(a, b):
        try:
            a = float(a)
            b = float(b)
            if not math.isfinite(a) or not math.isfinite(b) or b == 0:
                return float("nan")
            return a / b
        except Exception:
            return float("nan")

    @staticmethod
    def _eligible(f):
        try:
            if not f.has_fundamental_data or f.adjusted_price < 5 or f.dollar_volume < 1_000_000:
                return False
            sr = f.security_reference
            if sr.security_type != "ST00000001" or not sr.is_primary_share:
                return False
            if sr.exchange_id not in ("NYS", "NAS", "ASE"):
                return False
            # No sector/SIC exclusions are part of the frozen Stage-1 universe.
            # Names with missing factor inputs are removed later by the scoring
            # completeness rule, not by an undocumented industry filter.
            return True
        except Exception:
            return False

    def _snapshot(self, f):
        try:
            fs = f.financial_statements
            inc = fs.income_statement
            bs = fs.balance_sheet
            cf = fs.cash_flow_statement

            revenue = self._float(inc.total_revenue.twelve_months)
            gross_profit = self._float(inc.gross_profit.twelve_months)
            operating_income = self._float(inc.operating_income.twelve_months)
            assets = self._float(bs.total_assets.twelve_months)
            liabilities = self._float(bs.total_liabilities_net_minority_interest.twelve_months)
            operating_cf = self._float(cf.operating_cash_flow.twelve_months)
            capex = self._float(cf.capital_expenditure.twelve_months)
            shares = self._float(f.earning_reports.basic_average_shares.twelve_months)
            ev = self._float(f.company_profile.enterprise_value)

            gross_margin = self._safe_div(gross_profit, revenue)
            operating_margin = self._safe_div(operating_income, revenue)
            fcf = operating_cf - abs(capex) if math.isfinite(operating_cf) and math.isfinite(capex) else float("nan")
            fcf_margin = self._safe_div(fcf, revenue)
            leverage = self._safe_div(liabilities, assets)
            ev_sales = self._safe_div(ev, revenue)

            file_date = None
            try:
                file_date = fs.file_date.twelve_months
            except Exception:
                pass

            return {
                "revenue": revenue,
                "gross_margin": gross_margin,
                "operating_margin": operating_margin,
                "fcf_margin": fcf_margin,
                "leverage": leverage,
                "shares": shares,
                "ev_sales": ev_sales,
                "file_date": file_date,
            }
        except Exception:
            return None

    def _update_price(self, f):
        p = self._float(f.adjusted_price)
        if math.isfinite(p) and p > 0:
            self.price_history[f.symbol].append(p)

    def _is_rebalance_window(self):
        # First trading days of Jan/Apr/Jul/Oct. All information used here is
        # available on or before current algorithm date.
        if self.time.month not in (1, 4, 7, 10):
            return False
        qkey = (self.time.year, self.time.month)
        return qkey != self._last_qkey

    def _feature_row(self, f, snap):
        hist = self.quarter_history[f.symbol]
        if len(hist) < 4:
            return None
        prior = hist[-4][1]

        revenue_growth = self._safe_div(snap["revenue"], prior["revenue"])
        if math.isfinite(revenue_growth):
            revenue_growth -= 1
        pricing_power = (
            snap["gross_margin"] - prior["gross_margin"]
            if math.isfinite(snap["gross_margin"]) and math.isfinite(prior["gross_margin"])
            else (
                snap["operating_margin"] - prior["operating_margin"]
                if math.isfinite(snap["operating_margin"]) and math.isfinite(prior["operating_margin"])
                else float("nan")
            )
        )
        quality = (
            snap["fcf_margin"] - snap["leverage"]
            if math.isfinite(snap["fcf_margin"]) and math.isfinite(snap["leverage"])
            else (
                snap["operating_margin"] - snap["leverage"]
                if math.isfinite(snap["operating_margin"]) and math.isfinite(snap["leverage"])
                else float("nan")
            )
        )
        share_growth = self._safe_div(snap["shares"], prior["shares"])
        dilution = -(share_growth - 1) if math.isfinite(share_growth) else float("nan")
        valuation = -math.log1p(max(snap["ev_sales"], 0)) if math.isfinite(snap["ev_sales"]) else float("nan")

        px = list(self.price_history[f.symbol])
        if len(px) < 200:
            return None
        p_now = px[-1]
        p_6m = px[-126] if len(px) >= 126 else float("nan")
        p_12m = px[-252] if len(px) >= 252 else px[0]
        momentum12 = self._safe_div(p_now, p_12m)
        if math.isfinite(momentum12):
            momentum12 -= 1
        high52 = self._safe_div(p_now, max(px[-252:] if len(px) >= 252 else px))

        cik = None
        try:
            cik = str(f.company_reference.cik).strip().zfill(10)
        except Exception:
            pass
        net = self._network_asof(cik, self.time.date()) if cik else None
        scarcity = net["text_scarcity_raw"] if net else float("nan")

        return {
            "symbol": f.symbol,
            "cik": cik,
            "market_cap": self._float(f.market_cap),
            "demand_accel": revenue_growth,
            "pricing_power": pricing_power,
            "competitive_scarcity": scarcity,
            "quality": quality,
            "dilution": dilution,
            "valuation": valuation,
            "momentum12": momentum12,
            "high52": high52,
            "fund_file_date": snap["file_date"],
        }

    # ---------- Ranking ----------

    @staticmethod
    def _winsor_z(rows, feature):
        vals = [(i, r[feature]) for i, r in enumerate(rows) if math.isfinite(r.get(feature, float("nan")))]
        if len(vals) < 20:
            return {}
        raw = sorted(v for _, v in vals)
        lo = raw[max(0, int(0.01 * (len(raw) - 1)))]
        hi = raw[min(len(raw) - 1, int(0.99 * (len(raw) - 1)))]
        clipped = [(i, min(max(v, lo), hi)) for i, v in vals]
        xs = [v for _, v in clipped]
        mu = statistics.fmean(xs)
        sd = statistics.stdev(xs) if len(xs) > 1 else 0
        if sd <= 0:
            return {}
        return {i: (v - mu) / sd for i, v in clipped}

    def _score(self, rows):
        weights = self.MODEL_WEIGHTS[self.model_name]
        z = {feature: self._winsor_z(rows, feature) for feature in weights}
        scored = []
        for i, row in enumerate(rows):
            parts = []
            missing = False
            for feature, w in weights.items():
                if i not in z[feature]:
                    missing = True
                    break
                parts.append(w * z[feature][i])
            if missing:
                continue
            score = sum(parts)
            scored.append((score, row))
        return sorted(scored, key=lambda x: x[0], reverse=True)

    # ---------- Universe / trading ----------

    def _select_fundamentals(self, fundamentals):
        eligible = []
        for f in fundamentals:
            if not self._eligible(f):
                continue
            self._update_price(f)
            eligible.append(f)

        if not self._is_rebalance_window():
            return Universe.UNCHANGED

        self._last_qkey = (self.time.year, self.time.month)
        rows = []
        current_snaps = {}
        for f in eligible:
            snap = self._snapshot(f)
            if snap is None:
                continue
            current_snaps[f.symbol] = snap
            row = self._feature_row(f, snap)
            if row:
                rows.append(row)

        scored = self._score(rows)
        selected = scored[: self.top_n]

        for rank, (score, row) in enumerate(selected, 1):
            audit = {
                "formation_date": str(self.time.date()),
                "model": self.model_name,
                "top_n": self.top_n,
                "eligible_count": len(eligible),
                "feature_complete_count": len(rows),
                "scored_count": len(scored),
                "rank": rank,
                "score": score,
                "symbol": str(row["symbol"]),
                "cik": row.get("cik"),
            }
            for feature in self.MODEL_WEIGHTS[self.model_name]:
                audit[feature] = row.get(feature)
            audit["market_cap"] = row.get("market_cap")
            audit["fund_file_date"] = row.get("fund_file_date")
            self.audit_rows.append(audit)

        self._pending_targets = [r["symbol"] for _, r in selected]
        self._latest_scores = {r["symbol"]: s for s, r in selected}
        self._latest_feature_rows = {r["symbol"]: r for _, r in selected}
        self._selection_date = self.time.date()

        # Only after scoring do we append today's snapshot; otherwise current
        # data can leak into the t-4 "prior-year" slot.
        for symbol, snap in current_snaps.items():
            self.quarter_history[symbol].append((self.time.date(), snap))

        if not self._pending_targets:
            self.debug(f"{self.time.date()} no complete scored names")
            return Universe.UNCHANGED

        # Hold only selected securities to keep cloud memory manageable.
        return self._pending_targets

    def _rebalance_if_pending(self):
        if not self._pending_targets or self._selection_date != self.time.date():
            return

        targets = set(self._pending_targets)
        for kvp in self.portfolio:
            symbol = kvp.key
            holding = kvp.value
            if holding.invested and symbol not in targets and symbol != self.spy:
                self.liquidate(symbol, tag="quarterly exit")

        weight = 1.0 / len(self._pending_targets)
        for symbol in self._pending_targets:
            self.set_holdings(symbol, weight, tag=f"{self.model_name}:{self.top_n}")

        self.debug(
            f"{self.time.date()} rebalance model={self.model_name} n={len(self._pending_targets)}"
        )
        self._pending_targets = []

    def on_end_of_algorithm(self):
        key = (
            f"{self.project_id}/free_stage1/"
            f"bottleneck_{self.model_name}_top{self.top_n}_{self.algorithm_id}.csv"
        )
        saved = False
        if self.audit_rows:
            fields = list(self.audit_rows[0].keys())
            buf = io.StringIO()
            writer = csv.DictWriter(buf, fieldnames=fields, extrasaction="ignore")
            writer.writeheader()
            writer.writerows(self.audit_rows)
            saved = self.object_store.save(key, buf.getvalue())
        self.log(
            f"EVIDENCE_LABEL=FREE_DISCOVERY model={self.model_name} top_n={self.top_n} "
            f"one_way_cost_bps={self.one_way_cost_bps:.1f} "
            f"audit_rows={len(self.audit_rows)} audit_saved={saved} audit_key={key}"
        )
